apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-secrets
type: Opaque
stringData:
  VOYAGE_API_KEY: {{ .Values.voyageApiKey | quote }}
  GEMINI_API_KEY: {{ .Values.geminiApiKey | quote }}